name: GrassKernel
on: [push]
jobs:
  Build-A51-KSU:
    runs-on: ubuntu-latest
    steps:
      - name: Update the system
        run: sudo apt update
      - name: Install Dependencies
        run: sudo apt install -y bash git make libssl-dev curl bc pkg-config m4 libtool automake autoconf
      - name: Clone the repo
        run: git clone --depth 1 -b upstream https://github.com/Gojikovi/kernel_samsung_universal9611.git && cd kernel_samsung_universal9611 && ./download_toolchain.sh && ./build_kernel.sh aosp ksu
      - uses: actions/upload-artifact@v3
        with:
              name: Kernel
              run: cd kernel_samsung_universal9611
              path: $PWD/Kernel.zip
