name: GrassKernel
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Update the system
        run: pwd && sudo apt update && sudo apt upgrade
      - name: Install Dependencies
        run: sudo apt install -y bash git make libssl-dev curl bc pkg-config m4 libtool automake autoconf
      - name: Install toolchain
        run: ./download_toolchain.sh
      - name: Build the kernel
        run: ./build_kernel.sh aosp ksu
      - uses: actions/upload-artifact@v3
        with:
              name: my-artifact
              path: $PWD/Kernel.zip
